spring:
  profiles:
    active: dev # 기본 환경 선택

# dev 환경
---
spring:
  profiles: dev
  datasource:
    data: classpath:data-local.sql # 시작할때 실행시킬 script
    url: jdbc:mariadb://localhost:3306/toy
    username: testuser
    password: 1111
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

---
spring:
  profiles: test
  datasource:
    data: classpath:data-local.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081
---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8082
